name: CI

on:
  push:
    paths:
      - ".github/workflows/main.yml"
      - "sphinx/**"
      - "tests/**"
  pull_request:
    paths:
      - ".github/workflows/main.yml"
      - "sphinx/**"
      - "tests/**"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FORCE_COLOR: "1"
  PYTHONDEVMODE: "1"  # -X dev
  PYTHONWARNDEFAULTENCODING: "1"  # -X warn_default_encoding
  UV_SYSTEM_PYTHON: "1"  # make uv do global installs

jobs:
  deadsnakes-free-threraded:
    runs-on: ubuntu-latest
    name: Python ${{ matrix.python }} (Docutils ${{ matrix.docutils }}; free-threaded)
    strategy:
      fail-fast: false
      matrix:
        python:
        - "3.13-dev"
        docutils:
        - "0.20"
        - "0.21"

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python }} (deadsnakes)
      uses: deadsnakes/action@v3.2.0
      with:
        python-version: ${{ matrix.python }}
        nogil: true
    - name: Check Python version
      run: python --version --version
    - name: Install graphviz
      run: sudo apt-get install graphviz
    - name: Install dependencies
      run: |
        sudo python -m pip install --upgrade pip
        sudo python -m pip install .[test]
    - name: Install Docutils ${{ matrix.docutils }}
      run: sudo python -m pip install --upgrade "docutils~=${{ matrix.docutils }}.0"
    # markupsafe._speedups has not declared that it can run safely without the GIL
    - name: Remove markupsafe._speedups
      run: sudo rm -rf "$(sudo python -c 'from markupsafe._speedups import __file__ as f; print(f)')"
    - name: Test with pytest
      run: |
        ulimit -c unlimited
        sudo python -m pytest -vv --durations 25
        sudo chmod -R +rwx /cores/*
      env:
        PYTHONWARNINGS: "error"  # treat all warnings as errors

    - uses: actions/upload-artifact@master
      with:
        name: crashes
        path: /cores
