name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

env:
  FORCE_COLOR: "1"
  PYTHONDEVMODE: "1"  # -X dev
  PYTHONWARNDEFAULTENCODING: "1"  # -X warn_default_encoding
  UV_SYSTEM_PYTHON: "1"  # make uv do global installs

jobs:
  deadsnakes-free-threraded:
    runs-on: ubuntu-latest
    name: Python 3.13-dev (free-threaded)
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13-dev (deadsnakes)
      uses: deadsnakes/action@v3.2.0
      with:
        python-version: "3.13-dev"
        nogil: true
    - name: Check Python version
      run: python --version --version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[test]
    # markupsafe._speedups has not declared that it can run safely without the GIL
    - name: Remove markupsafe._speedups
      run: rm -rf "$(python -c 'from markupsafe._speedups import __file__ as f; print(f)')"
    - name: Test with pytest
      run: python -m pytest -vv --durations 25
      env:
        PYTHONWARNINGS: "error"  # treat all warnings as errors

  deadsnakes-free-threraded-core-dumps:
    runs-on: ubuntu-latest
    name: Python 3.13-dev (core-dump)
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13-dev (deadsnakes)
      uses: deadsnakes/action@v3.2.0
      with:
        python-version: "3.13-dev"
        nogil: true
    - name: Check Python version
      run: python --version --version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[test]
    # markupsafe._speedups has not declared that it can run safely without the GIL
    - name: Remove markupsafe._speedups
      run: rm -rf "$(python -c 'from markupsafe._speedups import __file__ as f; print(f)')"
    - name: Test with pytest
      run: |
        sudo mkdir -p /cores
        sudo chmod 777 /cores
        sudo bash -c 'echo "/cores/%e.%p.%t" > /proc/sys/kernel/core_pattern'
        ulimit -c unlimited
        python -m pytest --capture=tee-sys -vv --durations 25
      env:
        PYTHONWARNINGS: "error"  # treat all warnings as errors

    - uses: actions/upload-artifact@master
      if: always()
      with:
        name: crashes
        path: /cores
