name: CI

on:
  push:
    paths:
      - ".github/workflows/main.yml"
      - "sphinx/**"
      - "tests/**"
  pull_request:
    paths:
      - ".github/workflows/main.yml"
      - "sphinx/**"
      - "tests/**"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FORCE_COLOR: "1"
  PYTHONDEVMODE: "1"  # -X dev
  PYTHONWARNDEFAULTENCODING: "1"  # -X warn_default_encoding
  UV_SYSTEM_PYTHON: "1"  # make uv do global installs

jobs:
  deadsnakes:
    runs-on: ubuntu-latest
    name: Python ${{ matrix.python }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        python:
        - "3.14"

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Set up Python ${{ matrix.python }} (deadsnakes)
      uses: deadsnakes/action@v3.2.0
      with:
        python-version: ${{ matrix.python }}-dev
    - name: Check Python version
      run: python --version --version
    - name: Install graphviz
      run: sudo apt-get install --no-install-recommends --yes graphviz
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sed -i 's/flit_core>=3.7/flit_core @ git+https:\/\/github.com\/pypa\/flit.git#subdirectory=flit_core/' pyproject.toml
        python -m pip install .[test]
    - name: Test with pytest
      run: python -m pytest -n logical --dist=worksteal -vv --durations 25
      env:
        PYTHONWARNINGS: "error"  # treat all warnings as errors

  deadsnakes-free-threaded:
    runs-on: ubuntu-latest
    name: Python ${{ matrix.python }} (free-threaded)
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        python:
        - "3.14"

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Set up Python ${{ matrix.python }} (deadsnakes)
      uses: deadsnakes/action@v3.2.0
      with:
        python-version: ${{ matrix.python }}-dev
        nogil: true
    - name: Check Python version
      run: python --version --version
    - name: Install graphviz
      run: sudo apt-get install --no-install-recommends --yes graphviz
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sed -i 's/flit_core>=3.7/flit_core @ git+https:\/\/github.com\/pypa\/flit.git#subdirectory=flit_core/' pyproject.toml
        python -m pip install .[test]
    - name: Test with pytest
      run: python -m pytest -n logical --dist=worksteal -vv --durations 25
      env:
        PYTHONWARNINGS: "error"  # treat all warnings as errors
