name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  deadsnakes:
    runs-on: ubuntu-latest
    name: Python 3.14

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.14 (deadsnakes)
      uses: deadsnakes/action@v3.2.0
      with:
        python-version: "3.14-dev"
        debug: 'true'
    - name: Check Python version
      run: python --version --version
    - name: Run
      run: python -X dev -X warn_default_encoding -W error ./tests/test_crasher.py
