name: CI

on:
  push:
    paths:
      - ".github/workflows/main.yml"
      - "sphinx/**"
      - "tests/**"
  pull_request:
    paths:
      - ".github/workflows/main.yml"
      - "sphinx/**"
      - "tests/**"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FORCE_COLOR: "1"
  PYTHONDEVMODE: "1"  # -X dev
  PYTHONWARNDEFAULTENCODING: "1"  # -X warn_default_encoding
  UV_SYSTEM_PYTHON: "1"  # make uv do global installs

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    name: Python ${{ matrix.python }} (Docutils ${{ matrix.docutils }})
    strategy:
      fail-fast: false
      matrix:
        python:
        - "3.11"
        docutils:
        - "0.21"
#        include:
#        # test every supported Docutils version for the latest supported Python
#        - python: "3.12"
#          docutils: "0.20"

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    - name: Check Python version
      run: python --version --version
    - name: Install graphviz
      run: sudo apt-get install graphviz
    - name: Install uv
      run: >
        curl --no-progress-meter --location --fail
        --proto '=https' --tlsv1.2
        "https://astral.sh/uv/install.sh"
        | sh
    - name: Install dependencies
      run: uv pip install .[test]
    - name: Install Docutils ${{ matrix.docutils }}
      run: uv pip install --upgrade "docutils~=${{ matrix.docutils }}.0"
    - name: Test with pytest
      run: python -m pytest -vv --durations 25
      env:
        PYTHONWARNINGS: "error"  # treat all warnings as errors
