name: CI

on: [push, pull_request]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: "1"

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    name: Python ${{ matrix.python }} (Docutils ${{ matrix.docutils }})
    strategy:
      fail-fast: false
      matrix:
        python:
        - "3.8"
        - "3.9"
        - "3.10"
        - "3.11"
        - "3.12-dev"
        docutils:
        - "0.18"
        - "0.19"
        include:
        - python: "3"
          docutils: "HEAD"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      if: "!endsWith(matrix.python, '-dev')"
      with:
        python-version: ${{ matrix.python }}
    - name: Set up Python ${{ matrix.python }} (deadsnakes)
      uses: deadsnakes/action@v2.1.1
      if: "endsWith(matrix.python, '-dev')"
      with:
        python-version: ${{ matrix.python }}
    - name: Check Python version
      run: python --version
    - name: Install graphviz
      run: sudo apt-get install graphviz
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install nox
    - name: Test with pytest
      run: python -I -m nox --session tests-ci(docutils-${{ matrix.docutils }})

  windows:
    runs-on: windows-2019
    name: Windows

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install nox
    - name: Test with pytest
      run: python -I -m nox --session tests-ci(docutils-default)
