name: CI

on:
  push:
    paths:
      - ".github/workflows/main.yml"
      - "sphinx/**"
      - "tests/**"
  pull_request:
    paths:
      - ".github/workflows/main.yml"
      - "sphinx/**"
      - "tests/**"

permissions:
  contents: read

env:
  FORCE_COLOR: "1"
  PYTHONDEVMODE: "1"  # -X dev
  PYTHONWARNDEFAULTENCODING: "1"  # -X warn_default_encoding
  UV_SYSTEM_PYTHON: "1"  # make uv do global installs

jobs:
  deadsnakes:
    runs-on: ubuntu-latest
    name: Python 3.14
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Set up Python 3.14 (deadsnakes)
      uses: deadsnakes/action@v3.2.0
      with:
        python-version: 3.14-dev
    - name: Check Python version
      run: python --version --version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[test]
    - name: Test with pytest
      run: python -m pytest -vv
      env:
        PYTHONWARNINGS: "error"  # treat all warnings as errors
